[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
via_ir = true
solc_version = '0.8.29'
no-match-test = "testGas"
evm_version = "cancun"
remappings = [
  "node_modules/@hyperlane-xyz/:@openzeppelin/contracts/=node_modules/@hyperlane-xyz/core/node_modules/@openzeppelin/contracts/",
  "lib/hyperlane-monorepo/solidity/:@openzeppelin/contracts/=node_modules/@hyperlane-xyz/core/node_modules/@openzeppelin/contracts/",
  "@openzeppelin/contracts/=lib/uniswap-v4-periphery/lib/uniswap-v4-core/lib/openzeppelin-contracts/contracts/",
]

optimizer_runs = 20000

fs_permissions = [
  { access = "read", path = "./script/deployParameters/" },
  { access = "read-write", path = "./deployment-addresses/" },
]

additional_compiler_profiles = [
  { name = "manager", via_ir = true, optimizer_runs = 30000 },
]

compilation_restrictions = [
  { paths = "lib/v4-periphery/src/PositionManager.sol", optimizer_runs = 30000 },
]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[fmt]
line_length = 120
quote_style = 'single'

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fuzz]
runs = 5000

[rpc_endpoints]
base = "${BASE_RPC_URL}"
celo = "${CELO_RPC_URL}"
fraxtal = "${FRAXTAL_RPC_URL}"
ink = "${INK_RPC_URL}"
lisk = "${LISK_RPC_URL}"
metal = "${METAL_RPC_URL}"
mode = "${MODE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"
superseed = "${SUPERSEED_RPC_URL}"
swell = "${SWELL_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}"}
celo = { key = "${ETHERSCAN_API_KEY}"}
fraxtal = { key = "${ETHERSCAN_API_KEY}"}
optimism = { key = "${ETHERSCAN_API_KEY}"}

[profile.hardhat] # we have to use 4.9.6 here because of hyperlane
remappings = [
  "@openzeppelin/contracts/=node_modules/@hyperlane-xyz/core/node_modules/@openzeppelin/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
